### PR TITLE
Improve unit testing for put.go

### LINKED ISSUE #14: crossing-go Testing - put_test.go
Refactoring put.go
Conforming to the composition pattern in go to allow proper unit testing as per the following article. 
https://aws.amazon.com/blogs/developer/mocking-out-then-aws-sdk-for-go-for-unit-testing/

As of right now put_test.go does not work. Get put_test.go and improve the testing for put.go to include new output flag functionality.

### PR DESCRIPTION
**Pull request by clunaslunas**
Resolves #14 by adding build up and tear down to test version string output.

### CODE REVIEW

**Comment by danielc2013** [comment]
You now have the ability to create branches on this repo. Add this to a branch, then make the PR from your branch to https://github.com/stelligent/crossing-go/tree/v0.1.0

That branch will hold all the next features. So as not to break our releases

**Review by danielc2013 — CHANGES_REQUESTED** [review]
Along with my previous comments, the README needs to specify the version of Go to use and how to use go modules

**Comment by danielc2013** [comment]
Also, need to explain how to run the tests in the README. Maybe add a Makefile which can manage this?

**Comment by clunaslunas** [comment]
Mergine PR #19 and #16 into one PR

**Pull request closed without merging**
